### ISSUE TITLE
Error in the execution using oort as the sampler

### ISSUE THREAD

**Issue by ahmedcs** [SymbioticLab/Kuiper#1] opened 2021-06-16 09:14 UTC
Hello,

There is an issue with the execution of with the oort sampler which causes the program to stop.

Experiment: running google speech benchmark with the same configurations as set by default in the conf.yml in the repo. 

Error: probabilities do not sum to 1 thrown by resampleClients function of the parameter server: 

sampledClientsRealTemp = sorted(clientSampler.resampleClients(numToSample, cur_time=epoch_count))
https://github.com/SymbioticLab/Oort/blob/78fc6d08a1c6f428a8ad1b41b826865a35ba01e1/training/param_server.py#L377

Log output when running with 100 clients (stops every time at Epoch 24):

<img width="1375" alt="Screen Shot 2021-06-16 at 10 06 38 AM" src="https://user-images.githubusercontent.com/6817254/122192580-764e6000-ce9c-11eb-8ded-a80ae8db7cac.png">

Log output when running with 10 clients (stops at Epoch 329):

<img width="990" alt="Screen Shot 2021-06-16 at 11 40 08 AM" src="https://user-images.githubusercontent.com/6817254/122192405-4dc66600-ce9c-11eb-8096-f51211033c48.png">

**Comment by fanlai0990** [comment] 2021-06-28 04:30
Hi, ahmedcs,

Sorry for the late reply. This is very likely due to the insufficient number of clients in this dataset, so please try a larger dataset. We have fixed this issue in our [FedScale repo](https://github.com/SymbioticLab/FedScale).

We plan to update Oort soon (hopefully in the next few weeks) and make Oort be the execution backend of FedScale. In the meantime, feel free to use Fedscale, which supports Oort selector too. Please let us know if you have any questions!

**Comment by liecn** [comment] 2021-08-06 00:11
The error is caused by the function: random.choice(). Since the assigned weights for sampling do not sum to 1 (actually, it's all zeros). An intuitive method is to avoid the sampling by checking the sum of possibilities assigned to the function and stop the exploration processing when it's all zeros.

**Closed as completed** 2023-03-30 18:22 UTC
